version: '2'
services:
    entandomailplugin-app:
        image: entandomailplugin
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://entandomailplugin-postgresql:5432/entandoMailPlugin
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    entandomailplugin-postgresql:
        extends:
            file: postgresql.yml
            service: entandomailplugin-postgresql
