version: '2'
services:
    mailplugin-app:
        image: mailplugin
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mailplugin-postgresql:5432/mailPlugin
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    mailplugin-postgresql:
        extends:
            file: postgresql.yml
            service: mailplugin-postgresql
